#!/bin/bash

exec  2>&1

# Tell Tomcat where Java is
export JAVA_HOME={{pkgPathFor "core/jdk8"}}

# Tell Bamboo where its home dir is
export BAMBOO_HOME={{pkg.svc_data_path}}/bamboo

# Launch Bamboo in forground so the run hook doesn't terminate
exec {{pkg.path}}/bin/start-bamboo.sh -fg 2>&1